version: "3.8"

services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - fullstack

  backend:
    container_name: backend
    build: ./backend
    ports:
      - "4567:4567"
      - "8787:8787"
    expose:
      - "4567"
    environment:
      - MYSQL_USER=root
      - MYSQL_PASS=root
      - MYSQL_HOST=database
      - MYSQL_PORT=3306
    networks:
      - fullstack

  database:
    container_name: database
    build: ./database
    command: mysqld --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge